CC = g++
CFLAGS = -Wall -Wextra -Werror -std=c++11 -g
NAME = vec


all: $(NAME)

$(NAME):
	g++ -Wall -Wextra -Werror -std=c++11 -o $(NAME) vect22.cpp main2.cpp

clean:
	rm -f $(NAME)

re: clean all

.PHONY: all clean re

